version: '2'

services:
  featurebar:
    hostname: featurebar
    #restart: unless-stopped
    image: ghcr.io/concurrent-systems/crediverse/feature-bar:latest
    #build: ./featureBarImage
    volumes:
      - etcd_data:/default.etcd
      # - /localDirectory/etcd :/default.etcd # for a local directory mounted into the container as data direcotry for etcd
    ports:
      - 2379:2379 

volumes:
  etcd_data:
    driver: local
